### ISSUE TITLE
How to get policyId for alert conditions

### ISSUE THREAD

**Issue by rJunx** [hashicorp/cdktf-provider-newrelic#972]
Hello.

I am trying to set the policyId for alert conditions and set the channelId for alert policy. AlertPolicy and DataNewrelicAlertPolicy provide getter for id, but it returns string.

So how to get a number policyId for alert conditions?

**Comment by DanielMSchmidt** [comment]
Hey, sorry for the late response. To get the numeric policyId you need to wrap the policyId in `Fn.tonumber` and import Fn (`import {Fn} from "cdktf"`)
